SELECT J.JOB_TITLE AS `Cargo`, ROUND(AVG(E.SALARY), 2) AS `Média salarial`,
CASE
WHEN AVG(E.SALARY) > 10500 THEN 'CEO'
WHEN AVG(E.SALARY) > 7500 THEN 'Sênior'
WHEN AVG(E.SALARY) > 5800 THEN 'Pleno'
ELSE 'Júnior'
END AS `Senioridade`
FROM hr.jobs AS J
INNER JOIN hr.employees AS E
ON J.JOB_ID = E.JOB_ID
GROUP BY J.JOB_TITLE
ORDER BY AVG(E.SALARY), J.JOB_TITLE;
