SELECT
CONCAT(e.FIRST_NAME , ' ',  e.LAST_NAME) AS 'Nome completo',
DATE_FORMAT(j.START_DATE,'%d%m%Y')  AS 'Data de início',
DATE_FORMAT(j.END_DATE,'%d%m%Y')  AS 'Data de rescisão',
ROUND(TIMESTAMPDIFF(DAY, j.START_DATE, j.END_DATE)/365,2) AS 'Anos trabalhado'
FROM employees e
INNER JOIN job_history j ON j.EMPLOYEE_ID = e.EMPLOYEE_ID
ORDER BY CONCAT(e.FIRST_NAME , ' ',  e.LAST_NAME) ASC,
TIMESTAMPDIFF(DAY, j_START_DATE, COALESCE(j.END_DATE, CURRENT_DATE())) ASC;
