SELECT
	CONCAT(EJ.FIRST_NAME, ' ', EJ.LAST_NAME) AS `Nome completo`,
	EJ.JOB_TITLE AS 'Cargo',
    JH.START_DATE AS `Data de início do cargo`,
    D.DEPARTMENT_NAME AS 'Departamento'
FROM hr.job_history AS JH
LEFT JOIN(
SELECT E.FIRST_NAME, E.LAST_NAME, E.EMPLOYEE_ID, E.DEPARTMENT_ID, J.* FROM hr.employees AS E
LEFT JOIN hr.jobs as J
ON E.JOB_ID = J.JOB_ID
) AS EJ
ON JH.EMPLOYEE_ID = EJ.EMPLOYEE_ID
LEFT JOIN hr.departments AS D
ON EJ.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE EJ.FIRST_NAME  IS NOT NULL
ORDER BY `Nome completo` DESC, 'Cargo';
