
SELECT CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME) `Nome completo`, J.JOB_TITLE Cargo,
JH.START_DATE `Data de início do cargo`, D.DEPARTMENT_NAME Departamento 
FROM employees EMP
INNER JOIN job_history JH
ON EMP.EMPLOYEE_ID = JH.EMPLOYEE_ID
INNER JOIN departments D
ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN jobs J
ON JH.JOB_ID = J.JOB_ID
ORDER BY CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME) DESC, J.JOB_TITLE;
