SELECT j.JOB_TITLE 'Cargo', ROUND(AVG(e.SALARY), 2) 'Média salarial',
CASE
WHEN (ROUND(AVG(e.SALARY), 2) <= 5800 AND ROUND(AVG(e.SALARY), 2) >= 2000) THEN 'Júnior'
WHEN (ROUND(AVG(e.SALARY), 2) > 5800 AND ROUND(AVG(e.SALARY), 2) <= 7500) THEN 'Pleno'
WHEN (ROUND(AVG(e.SALARY), 2) > 7500 AND ROUND(AVG(e.SALARY), 2) <= 10500) THEN 'Sênior'
WHEN (ROUND(AVG(e.SALARY), 2) > 10500) THEN 'CEO'
END AS 'Senioridade'
FROM hr.employees e
INNER JOIN hr.jobs j
ON e.JOB_ID = j.JOB_ID
GROUP BY j.JOB_TITLE
ORDER BY ROUND(AVG(e.SALARY), 2), j.JOB_TITLE;
