DELIMITER $$

CREATE FUNCTION buscar_quantidade_de_empregos_por_funcionario(IN email VARCHAR(50))
BEGIN
  SELECT COUNT(JH.EMPLOYEE_ID)
  FROM job_history AS JH
  INNER JOIN employees AS E
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
  GROUP BY JH.DEPARTMENT_ID
  HAVING JH.DEPARTMENT_ID = 90;
END $$

DELIMITER ;
