USE hr
DELIMITER $$
CREATE PROCEDURE buscar_media_por_cargo(IN cargo VARCHAR(100))
BEGIN
SELECT ROUND(AVG(E.SALARY), 2) AS 'Média salarial'
FROM hr.employees AS E
INNER JOIN hr.jobs AS J
WHERE J.JOB_TITLE LIKE cargo AND J.JOB_ID = E.JOB_ID;
END$$
DELIMITER ;
