SELECT JOB_TITLE AS Cargo, (
  SELECT CASE
  WHEN MAX_SALARY BETWEEN 5000 AND 10000 THEN 'Baixo'
  WHEN MAX_SALARY BETWEEN 10001 AND 20000 THEN 'Médio'
  WHEN MAX_SALARY BETWEEN 20001 AND 30000 THEN 'Alto'
  ELSE 'Altíssimo'
  END
  FROM hr.jobs AS J
  WHERE j.JOB_ID = J.JOB_ID
) AS `Nível`
FROM hr.jobs AS j
ORDER BY Cargo ASC;
