SELECT
CONCAT(t2.FIRST_NAME, ' ',t2.LAST_NAME) AS 'Nome completo',
CASE
WHEN DAY(t1.START_DATE)<10 && MONTH(t1.START_DATE)<10 THEN CONCAT('0',DAY(t1.START_DATE),'/0',MONTH(t1.START_DATE), '/',YEAR(t1.START_DATE))
WHEN DAY(t1.START_DATE)<10 && MONTH(t1.START_DATE)>=10 THEN CONCAT('0',DAY(t1.START_DATE),'/',MONTH(t1.START_DATE), '/',YEAR(t1.START_DATE))
WHEN DAY(t1.START_DATE)>=10 && MONTH(t1.START_DATE)<10 THEN CONCAT(DAY(t1.START_DATE),'/0',MONTH(t1.START_DATE), '/',YEAR(t1.START_DATE))
ELSE CONCAT(DAY(t1.START_DATE),'/',MONTH(t1.START_DATE), '/',YEAR(t1.START_DATE))
END AS 'Data de início',
CASE
WHEN DAY(t1.END_DATE)<10 && MONTH(t1.END_DATE)<10 THEN CONCAT('0',DAY(t1.END_DATE),'/0',MONTH(t1.END_DATE), '/',YEAR(t1.END_DATE))
WHEN DAY(t1.END_DATE)<10 && MONTH(t1.END_DATE)>=10 THEN CONCAT('0',DAY(t1.END_DATE),'/',MONTH(t1.END_DATE), '/',YEAR(t1.END_DATE))
WHEN DAY(t1.END_DATE)>=10 && MONTH(t1.END_DATE)<10 THEN CONCAT(DAY(t1.END_DATE),'/0',MONTH(t1.END_DATE), '/',YEAR(t1.END_DATE))
ELSE CONCAT(DAY(t1.END_DATE),'/',MONTH(t1.END_DATE), '/',YEAR(t1.END_DATE))
END AS 'Data de rescisão',
ROUND(DATEDIFF(t1.END_DATE, t1.START_DATE)/365,2) AS 'Anos trabalhados'
FROM hr.job_history AS t1
INNER JOIN hr.employees AS t2
ON t1.EMPLOYEE_ID = t2.EMPLOYEE_ID
ORDER BY t2.FIRST_NAME, DATEDIFF(t1.END_DATE, t1.START_DATE);
